//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WatchStoreEntities9 : DbContext
    {
        public WatchStoreEntities9()
            : base("name=WatchStoreEntities9")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admin { get; set; }
        public virtual DbSet<Brand> Brand { get; set; }
        public virtual DbSet<Category> Category { get; set; }
        public virtual DbSet<Customer> Customer { get; set; }
        public virtual DbSet<Detail> Detail { get; set; }
        public virtual DbSet<district> district { get; set; }
        public virtual DbSet<Feedback> Feedback { get; set; }
        public virtual DbSet<Images_Certification> Images_Certification { get; set; }
        public virtual DbSet<Images_Default> Images_Default { get; set; }
        public virtual DbSet<Images_Reality> Images_Reality { get; set; }
        public virtual DbSet<Order> Order { get; set; }
        public virtual DbSet<OrderItem> OrderItem { get; set; }
        public virtual DbSet<OTP> OTP { get; set; }
        public virtual DbSet<Product> Product { get; set; }
        public virtual DbSet<province> province { get; set; }
        public virtual DbSet<Supplier> Supplier { get; set; }
        public virtual DbSet<Video> Video { get; set; }
        public virtual DbSet<Voucher> Voucher { get; set; }
        public virtual DbSet<wards> wards { get; set; }
    }
}
